language: node_js
node_js:
  - 6

cache:
  yarn: true
  directories:
    - webapp/node_modules
    - native/node_modules

script:
  - cd webapp
  - yarn
  - yarn test
  - cd ..
  - cd native
  - yarn
  - yarn test